name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        go_version: [ '1.17', '1.18' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        include:
          - os: ubuntu-latest
            services:
              proxy:
                image: abhinavsingh/proxy.py:v2.4.4
                ports:
                  - "8899:8899"
          - os: windows-latest
            services: {}
          - os: macOS-latest
            services: {}

    services: ${{ matrix.services }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use GO ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Test GO ${{ matrix.go_version }}
        run: PROXY_URL=http://localhost:8899 go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload to codecov
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.go_version == '1.17' }}
        run: bash <(curl -s https://codecov.io/bash)